export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#fed7aa",
        "on-surface-variant": "#57534e",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#fde68a",
        "surface-container-low": "#f5f2eb",
        "primary": "#1c1917",
        "surface-dim": "#d6d3d1",
        "inverse-surface": "#292524",
        "on-tertiary-container": "#c2410c",
        "on-tertiary": "#ffffff",
        "tertiary": "#7c2d12",
        "surface-bright": "#faf8f5",
        "on-secondary": "#ffffff",
        "surface-container-high": "#ece8de",
        "on-surface": "#1c1917",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#78350f",
        "on-primary": "#ffffff",
        "background": "#faf8f5",
        "secondary-container": "#fef3c7",
        "primary-fixed": "#ffedd5",
        "secondary": "#b45309",
        "tertiary-fixed-dim": "#fed7aa",
        "error": "#ba1a1a",
        "on-background": "#1c1917",
        "surface-tint": "#b45309",
        "on-secondary-fixed": "#451a03",
        "on-tertiary-fixed": "#431407",
        "tertiary-container": "#ffedd5",
        "on-error": "#ffffff",
        "on-primary-fixed": "#431407",
        "primary-container": "#292524",
        "on-primary-container": "#d6d3d1",
        "on-tertiary-fixed-variant": "#9a3412",
        "inverse-primary": "#fed7aa",
        "surface-container-highest": "#e7e2d6",
        "surface": "#faf8f5",
        "on-secondary-container": "#78350f",
        "outline-variant": "#e7e5e4",
        "surface-variant": "#e7e2d6",
        "inverse-on-surface": "#faf8f5",
        "secondary-fixed": "#fef3c7",
        "on-secondary-fixed-variant": "#92400e",
        "surface-container": "#f0ebe1",
        "tertiary-fixed": "#ffedd5",
        "outline": "#78716c"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "space-lg": "1rem",
        "space-sm": "0.5rem",
        "margin": "1rem",
        "gutter-split": "0.5rem",
        "space-md": "0.75rem",
        "space-xs": "0.25rem",
        "gutter": "0.75rem",
        "space-xl": "1.5rem"
      },
      fontFamily: {
        "label-caps": ["Public Sans"],
        "headline-sm": ["Public Sans"],
        "body-lg": ["Inter"],
        "mono-data": ["JetBrains Mono"],
        "mono-data-sm": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "headline-md": ["Public Sans"],
        "body-sm": ["Inter"],
        "headline-lg": ["Public Sans"]
      },
      fontSize: {
        "label-caps": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "mono-data": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "mono-data-sm": ["11px", { lineHeight: "14px", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    }
  }
}
